#!/bin/bash

# This is a thin wrapper around bogcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using bogcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_BOGCOIND

# Grab the value of $REAL_BOGCOINCLI which may be bogcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_BOGCOINCLI}" "$@" | sed 's/\r//'
